- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.homelab.lan
        description: Movies & TV Shows
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}

    - Books:
        icon: calibre-web.png
        href: http://books.homelab.lan
        description: E-book Library
        widget:
          type: calibreweb
          url: http://calibre-web:8083
          username: {{HOMEPAGE_VAR_CALIBREWEB_USERNAME}}
          password: {{HOMEPAGE_VAR_CALIBREWEB_PASSWORD}}

    - Transmission:
        icon: transmission.png
        href: http://transmission.homelab.lan
        description: Torrent Client
        widget:
          type: transmission
          url: http://transmission:9091
          rpcUrl: /transmission/
          username: {{HOMEPAGE_VAR_TRANSMISSION_USERNAME}}
          password: {{HOMEPAGE_VAR_TRANSMISSION_PASSWORD}}

- Infrastructure:
    - Proxmox:
        icon: proxmox.png
        href: https://homelab.lan:8006
        description: Virtual Machine Manager
        widget:
          type: proxmox
          url: https://homelab.lan:8006
          username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
          node: homelab

    - Portainer:
        icon: portainer.png
        href: http://portainer.homelab.lan
        description: Container Management
        widget:
          type: portainer
          url: http://portainer:9000
          env: 3
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}

    - Traefik:
        icon: traefik.png
        href: http://traefik.homelab.lan
        description: Reverse Proxy
        widget:
          type: traefik
          url: http://traefik.homelab.lan
