services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.homelab.lan`)"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_CACHE_SIZE_MB=128
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - /mnt/docker-data/transmission/config:/config
      - /mnt/docker-data/transmission/downloads/incomplete:/downloads/incomplete
      - /mnt/docker-data/transmission/watch:/watch
      - /mnt/nas-media/downloads:/downloads/complete
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
